language: node_js
node_js:
  - "node"
install:
  - npm --prefix ./favour-trader install ./favour-trader
  - npm --prefix ./favour-trader/client install ./favour-trader/client
script:
  - cd favour-trader
  - npm test
  - npm run devServer
  - cd client
  - npm test
  - npm start
  - npm run e2etest